[providers]
python = "python"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
dependsOn = ["python"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python -m gunicorn simple_app:app --bind 0.0.0.0:$PORT"
