[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt --no-cache-dir"

[deploy]
startCommand = "sh -c 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 2'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
