services:
  - type: web
    name: mortgage-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: FLASK_ENV
        value: testing
      - key: SECRET_KEY
        value: "8f42a73f4f56c124c62f5da9e7f2db23a09a5f952b9c42af"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PATH
        value: /opt/render/project/python/venv/bin:/opt/render/project/.venv/bin:/opt/render/project/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    healthCheckPath: /health
    healthCheckTimeout: 5
    autoDeploy: true
